### ISSUE TITLE
TableLayout issue

### ISSUE THREAD

**Issue by AnotherEnd15** [FanTranslatorsInternational/ImGui.Forms#2]
![image](https://user-images.githubusercontent.com/29506629/220246579-cb7516a5-282c-4b79-87a6-1bcc1b9e6943.png)
Code:

>     public static Component Resolve(object obj)
    {
        var stackLayout = new TableLayout
        {
            VerticalAlignment = VerticalAlignment.Top,
            Spacing = new Vector2(10, 10),
            
        };
        foreach (var v in obj.GetType().GetFields())
        {
            var row = new TableRow();
            row.Cells.Add(Resolve(obj,v));
            stackLayout.Rows.Add(row);
        }

        return stackLayout;
    }

It looks like the Spacing between the rows of the TableLayout is not Vector2(10,10) .

**Comment by AnotherEnd15** [comment]
Environment: .net 6 ConsoleApp
![image](https://user-images.githubusercontent.com/29506629/220248091-79dc0218-9064-4952-943e-940547f3befb.png)

**Comment by onepiecefreak3** [comment]
Since I don't know how you set up those cell components, based on your image, I assume you used at least 3 stack layouts. StackLayouts, by default, always scale to the space. They have to explicitly be set up to not do that by setting their Size to Size.Content, for example.

Scaling to the remaining space in this framework means, that it distributes the remaining space equally between components by default, that have no fixed size, like layout components. Elements with fixed sizes in height are Labels or textboxes, for example. I assume those are 3 layout components in your image. This means, the space in the TableLayout is distributed 33% to each StackLayout component. You can adjust that distribution by setting a Size with relative, instead of absolute, witdth and height that state different scales

If you set each one to Size.Content, this should make them appear right after the other, with the Spacing of the TableLayout applied, of course.

Examples:
```
stackLayout1.Size = new Size(SizeValue.Content, SizeValue.Relative(.5f));
stackLayout2.Size = new Size(SizeValue.Content, SizeValue.Relative(.1f));
stackLayout3.Size = new Size(SizeValue.Content, SizeValue.Relative(.4f));
```

Here, all stack layouts would fit their content in width, but scale to 50%, 10%, and 40% in height in the parent layout component respectively. Those relative values do NOT have to add up to 1f, but it is recommended in a static setup to not lose track of the size relations. If you do a dynamic setup, like yours it seems, you have to gauge what height is best for you. 10% for every layout to have a constant sizing? Or just fit the content? whatever you may need, just play around with the Size and SizeValues. They are half the work you have to put into the layout.
